### ISSUE TITLE
run_all_checks inaccurate warning

### ISSUE THREAD

**Issue by harriscw** [pharmaverse/sdtmchecks#306]
This warning kicks off for `run_all_checks` even when there is no issue for roche users who use `roche_covid_df()`.

https://github.com/pharmaverse/sdtmchecks/blob/44f42f775635bcb4f1b1c3a7aab914868a398c88/R/run_all_checks.R#L98

I ran `run_all_checks` just now using the correct pipeline and get this warning even though covid related checks run. 
 `roche_covid_df` looks at TS to get meddra version then uses appropriate terms from a bunch of files that are assumed to have been read in.  So `covid_df` itself is not needed for `run_all_checks`, just whatever `roche_covid_df()` needs.

I think the simplest update would be expand the `if()` condition of this warning to encompass `roche_covid_df()`'s input needs

**Comment by jimrothstein** [comment]
#306
-  The  covid_df  `if`   in   `run_all_checks`  is run  AFTER     all the checks have been run  with mcapply
-  So I think  running  the  covid `if` (and any other critieria)  BEFORE and then adjusting `metads`  will help  with this problem 
- Since I am  new,   this might be a bit much for me.   But I would like to take look.

**Comment by harriscw** [comment]
With the removal of `covid_df` I think this issue is now closed
